# Generated by Django 3.2 on 2021-05-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='Image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
