# Generated by Django 3.2 on 2021-05-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_advertisement_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='Image',
        ),
    ]
