# Generated by Django 3.2 on 2021-05-31 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0003_remove_advertisement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='Image',
            field=models.ImageField(null=True, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='Poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
