# Generated by Django 3.2 on 2021-06-01 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=150)),
                ('Last_Name', models.CharField(max_length=150)),
                ('Image', models.ImageField(null=True, upload_to='pictures')),
                ('Phone', models.CharField(max_length=20)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.district')),
                ('Division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.division')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
