# Generated by Django 3.2 on 2021-06-02 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='District',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Division',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='User',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
