# Generated by Django 3.2 on 2021-06-09 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_advertisement_books_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='Division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.division'),
        ),
    ]
